.PHONY: clean All

All:
	@echo "----------Building project:[ GeeksForGeeks - Release ]----------"
	@cd "GeeksForGeeks" && "$(MAKE)" -f  "GeeksForGeeks.mk"
clean:
	@echo "----------Cleaning project:[ GeeksForGeeks - Release ]----------"
	@cd "GeeksForGeeks" && "$(MAKE)" -f  "GeeksForGeeks.mk" clean
