.PHONY: clean All

All:
	@echo "----------Building project:[ cppGeeksForGeeks - Debug ]----------"
	@cd "cppGeeksForGeeks" && "$(MAKE)" -f  "cppGeeksForGeeks.mk"
clean:
	@echo "----------Cleaning project:[ cppGeeksForGeeks - Debug ]----------"
	@cd "cppGeeksForGeeks" && "$(MAKE)" -f  "cppGeeksForGeeks.mk" clean
