.PHONY: clean All

All:
	@echo "----------Building project:[ DSAndAlgorithm - Debug ]----------"
	@$(MAKE) -f  "DSAndAlgorithm.mk"
clean:
	@echo "----------Cleaning project:[ DSAndAlgorithm - Debug ]----------"
	@$(MAKE) -f  "DSAndAlgorithm.mk" clean
